spring:
  application:
    name: gateway
  profiles:
    active: dev
  jwt:
    secret: sksmsdydxordldiznjzkfkrhehqnfflwleprtmdkslazzxortmdlazztrdyddlrjsqlalfqjsghdia
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalCors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
              - "http://localhost:8081"
              - "http://localhost:8080"
              - "http://localhost:8083"
            allow-credentials: true
            allowed-headers:
              - '*'
            allowed-methods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka
      #,http://admin:1234@localhost:8762/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: debug
